package com.izv.dam.keep.pojo;
// Generated 09-feb-2016 13:27:24 by Hibernate Tools 4.3.1

import android.database.Cursor;
import android.os.Parcel;
import android.os.Parcelable;

import com.izv.dam.keep.bd.Contrato;

/**
 * Keep generated by hbm2java
 */
public class Keep implements Parcelable{

    private long id;
    private Usuario usuario;
    private int idWeb;
    private String contenido;
    private String ruta;
    private boolean estado;

    public Keep() {
    }



    public Keep(long id, String contenido, boolean estado, int idWeb) {
        this.id = id;
        this.contenido = contenido;
        this.estado = estado;
        this.idWeb = idWeb;
    }


    protected Keep(Parcel in) {
        usuario = in.readParcelable(Usuario.class.getClassLoader());
        contenido = in.readString();
        ruta = in.readString();
        estado = in.readByte() != 0;
    }

    public void set(Cursor c){
        setId(c.getLong(c.getColumnIndex(Contrato.TablaKeep._ID)));
        setContenido(c.getString(c.getColumnIndex(Contrato.TablaKeep.CONTENIDO)));

        if(c.getInt(c.getColumnIndex(Contrato.TablaKeep.ESTADO))==1){
            setEstado(true);
        }else {
            setEstado(false);
        }
    }

    public static final Creator<Keep> CREATOR = new Creator<Keep>() {
        @Override
        public Keep createFromParcel(Parcel in) {
            return new Keep(in);
        }

        @Override
        public Keep[] newArray(int size) {
            return new Keep[size];
        }
    };

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }



    public String getContenido() {
        return this.contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    public String getRuta() {
        return this.ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    public boolean getEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getIdWeb() {
        return idWeb;
    }

    public void setIdWeb(int idWeb) {
        this.idWeb = idWeb;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeParcelable(usuario, flags);
        dest.writeString(contenido);
        dest.writeString(ruta);
        dest.writeByte((byte) (estado ? 1 : 0));
    }

    @Override
    public String toString() {
        return "Keep{" +
                "id=" + id +
                ", usuario=" + usuario +
                ", idWeb=" + idWeb +
                ", contenido='" + contenido + '\'' +
                ", ruta='" + ruta + '\'' +
                ", estado=" + estado +
                '}';
    }
}
